### ISSUE TITLE
Glacier2.PermissionDeniedException: Password check failed

### ISSUE THREAD

**Issue by dominikl** [ome/omero-gateway-java#66]
"Password check failed" after already being logged in. Can't imagine how that happens. Need more info on how to replicate if possible.

[QA 31193](https://www.openmicroscopy.org/qa2/qa/feedback/31193/)

```
Caused by: omero.gateway.exception.DSOutOfServiceException: Failed to create connector
	at omero.gateway.Gateway.createConnector(Gateway.java:1789)
	at omero.gateway.Gateway.getConnector(Gateway.java:1659)
	at omero.gateway.Gateway.getPojosService(Gateway.java:704)
	at omero.gateway.facility.BrowseFacility.getHierarchy(BrowseFacility.java:146)
	... 12 more

Caused by: Glacier2.PermissionDeniedException
    reason = "Password check failed for
```

**Comment by dominikl** [comment]
From the submitter:
"I was trying to upload a rather big dataset (approx 400GB) that included several folders and sub-folders. While doing so, the uploader reported that several errors occurred, so I cancelled the upload, which did not seem to work, which is when I seemingly lost connection to OMERO. I tried the same procedure again afterwards (twice actually) with the same errors and results. Uploading the folders one by one did worked successfully in the end."
Maybe it's rather Insight than gateway related? Have to try to reproduce.

**Comment by jburel** [comment]
What are the errors? Did they occur during the scanning of the folders? If this is the case it is more likely a BioFormats issue

**Comment by dominikl** [comment]
Another one, triggered from a different route. Same person though. Wonder if it has something to do with their setup...
[QA 31196](https://www.openmicroscopy.org/qa2/qa/feedback/31196/)

**Comment by dominikl** [comment]
Another one, different location, different stacktrace [QA 31206](https://www.openmicroscopy.org/qa2/qa/feedback/31206/).
